### ISSUE TITLE
Cannot close Setup (Optional) page

### ISSUE THREAD

**Issue by Taverius** [NiklasGollenstede/re-style#10]
I was trying to setup ff60 to see if I could switch from waterfox.

I cant get native-ext to run (unsupported 16-bit blah blah) and now the ff install cannot be used because the restyle option page in question immediately switches to itself if i change to another tab, and always reopens itself (and another 2-4 restyle option tabs) if i close it.

I mean, I'll restart with addons disabled and turn it off, but yeah that's a thing, you're being a little aggressive with grabbing focus here.

**Comment by NiklasGollenstede** [comment]
Yeah, I shot myself in the knee with that once as well.
I need to rethink (and implement) the entire `native-ext` setup before it completely breaks in Firefox 61 (release on June 26th). This will be part of it.

**Comment by NiklasGollenstede** [comment]
reStyle v0.4.0 is released on AMO and won't automatically open the setup page anymore. It displays a clickable notification instead. (And shouldn't be caught in an infinite retry loop anyway.)
If you need help with the 16-bit issue, feel free to ask!
