### ISSUE TITLE
Extract styles from popular sites

### ISSUE THREAD

**Issue by Madis0** [NiklasGollenstede/re-style#13]
In order to make the process even smoother for the user, have you considered extracting the styles from popular sites? 
By extracting I mean getting the raw CSS without requiring the user to navigate there (assuming they navigate to the preview page). 

Sites it could support initially:
- userstyles.org
- github.com
- gitlab.com
- openusercss.org

**Comment by NiklasGollenstede** [comment]
There already is some URL translating in place. When visiting a style on USO or GitHub, the URL in the panel will automatically be replaced with that of the actual style file:

https://github.com/NiklasGollenstede/re-style/blob/master/background/remote/map-url.js

Is that what you mean? It could obviously be extended to include more sites. And having a color indicator on the icon that a style is available would also be nice ...

**Comment by Madis0** [comment]
That is what I meant, but when I try it I get an unexpected MIME-type error (as it gets the html, not css).
![image](https://user-images.githubusercontent.com/8611110/43685801-86095af8-98c2-11e8-9318-92d7b250ec5b.png)


Edit: my bad, tried installing without looking at it. It does work with CSS on GitHub after all.

**Comment by NiklasGollenstede** [comment]
I added basic support for `openusercss.org` and `gitlab.com`. Do you know an example user style on GitLab?

**Comment by Madis0** [comment]
Yes, I am working on reStyle-compatible UI styles here: https://gitlab.com/Madis0/Firefox-tweaks
Edit: tested, doesn't seem to work there without opening the raw file.

**Comment by NiklasGollenstede** [comment]
Your repo contains some cool snippets, thanks for that!
Here is one you might want to add (moves the reload button into the URL bar):
https://github.com/NiklasGollenstede/user-styles/blob/master/developer-edition-dark.css#L172-L189

---

The repo I tested it on had more path segments before the `/blob/master/`. It's fixed in v`0.4.1b23`.

I think we are done here. Thanks for your input!
