### ISSUE TITLE
Enable flag on 69+

### ISSUE THREAD

**Issue by Madis0** [NiklasGollenstede/re-style#22]
In Firefox 69, `toolkit.legacyUserProfileCustomizations.stylesheets` must be set to `true` in `about:config`. The extension should either do it automatically, check for it (if possible) or simply instruct the users.
https://www.reddit.com/r/firefox/comments/brttne/psa_firefox_v69_users_will_have_to_set_a_pref_to/

**Comment by NiklasGollenstede** [comment]
Thank you for informing me!
This can actually be (and now is) done fully automatically.
