### ISSUE TITLE
not working for 64bit windows 10

### ISSUE THREAD

**Issue by ShiinaScripts** [NiklasGollenstede/re-style#7]
https://comfy.moe/dfxcpp.png

here is the issue

**Comment by ShiinaScripts** [comment]
Fixed by running native ext from same disk as firefox installation

**Comment by NiklasGollenstede** [comment]
> Fixed by running native ext from same disk as firefox installation

Good to hear that it works now, I'm curious to know what exactly you mean by "running native ext from same disk as firefox installation".
NativeExt always installs into your `AppData` (which, unless you seriously mess with Windows, is on the primary drive, which is usually `C:\`).
So did you move your Firefox installation or how did you run "from same disk"?

**Comment by ShiinaScripts** [comment]
My default download directory is F:/ And firefox is on C:/
so I moved it from the downloads to somewhere on C:/
